<?php
            session_start();
            ?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fetch Roadmap Image</title>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="./css/style.css">
    <style>
         /* Custom CSS for Loader */
         .loader {
            border: 4px solid rgba(0, 0, 0, 0.1);
            border-top-color: #3498db;
            border-radius: 50%;
            width: 40px;
            height: 40px;
            animation: spin 1s ease-in-out infinite;
        }
        @keyframes spin {
            to {
                transform: rotate(360deg);
            }
        }
        .loader-overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
            background: rgba(255, 255, 255, 0.8);
            z-index: 9999;
        }
    </style>
     <script>
        // JavaScript to handle loader visibility
        document.addEventListener("DOMContentLoaded", function() {
            const loader = document.getElementById('loader');
            setTimeout(function() {
                loader.style.display = 'none';
            }, 1000); // Hides the loader after 1 second
        });
    </script>
</head>

<body class="flex flex-col min-h-screen bg-gray-100 text-gray-800">
 <!-- Loader HTML -->
 <div id="loader" class="loader-overlay">
        <div class="loader"></div>
    </div>
    <!-- Navigation Bar -->
    <header class="text-white-600 body-font" style="background-color: black; font-family: Oswald, sans-serif">
        <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
            <a class="flex title-font font-medium items-center text-white-900 mb-4 md:mb-0">
                <img src="./img/logo.png" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" style="width: 208px; height: auto; max-height: 80px;">
                <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </a>
            <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center" style="color: white; font-size:large">
                <a class="mr-6 hover:text-blue-900" href="index.php">Home</a>
                <a class="mr-6 hover:text-blue-900" href="index.php/#about">About</a>
                <a class="mr-6 hover:text-blue-900" href="contact.php">Contact</a>
                <a class="mr-6 hover:text-blue-900" href="index.php/#services">Services</a>
                <a class="mr-6 hover:text-blue-900" href="roadmap.php">Roadmap</a>
            </nav>
        </div>
    </header>

    <div class="container mx-auto flex-grow px-4 py-8">
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
            <strong class="font-bold">Note:</strong>
            <span class="block sm:inline">Some roadmaps are generated by AI and have not been verified by roadmap.sh. However, we ensure they contain no major errors. Other roadmaps are verified by roadmap.sh. <br>If you have any questions, please contact us through the Contact Page. If you do not find the required roadmap, feel free to reach out to us.<br> If you don't find the roadmap then search it with ".jpg" Extension. Just like if search Java then just use "java.jpg".</span>
        </div>
        <br>
        <div class="search-form max-w-md mx-auto bg-white p-6 rounded-lg shadow-md">
            <h2 class="text-2xl font-bold mb-4">Search Roadmap Image</h2>
            <form action="fetch.php" method="post" class="space-y-4">
                <input type="text" name="roadmap_name" placeholder="Enter roadmap name" required class="w-full p-3 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500">
                <input type="submit" name="submit" value="Search" class="w-full p-3 bg-blue-500 text-white rounded hover:bg-blue-600 cursor-pointer">
            </form>
        </div>

        <div class="result mt-8 text-center">
            <?php
           
            if (isset($_SESSION['file_name']) && isset($_SESSION['file_type']) && isset($_SESSION['file_data'])) {
                $file_name = htmlspecialchars($_SESSION['file_name'], ENT_QUOTES, 'UTF-8');
                $file_type = htmlspecialchars($_SESSION['file_type'], ENT_QUOTES, 'UTF-8');
                $file_data = htmlspecialchars($_SESSION['file_data'], ENT_QUOTES, 'UTF-8');

                echo "<h2 class='text-xl font-semibold mb-4'>Result for: $file_name</h2>";
                echo "<img src='data:$file_type;base64,$file_data' alt='$file_name' class='max-w-full h-auto mx-auto'>";

                // Generate download link
                echo "<a href='data:$file_type;base64,$file_data' download='$file_name' class='mt-4 inline-block px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 cursor-pointer'>Download</a>";

                // Clear the session data
                unset($_SESSION['file_name'], $_SESSION['file_type'], $_SESSION['file_data']);
            }
            ?>
        </div>
    </div>

    <!-- Footer -->
    <footer class="bg-gray-800 text-white text-center py-6 mt-auto">
        <ul class="flex justify-center space-x-4">
            <li><a href="roadmap.php" class="hover:underline">Roadmap</a></li>
            <li><a href="stream.php" class="hover:underline">Stream Information</a></li>
        </ul>
    </footer>
</body>

</html>
